# Generated by Django 5.2.5 on 2025-09-04 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_delete_medicalrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(choices=[('GENERALDOCTOR', 'generaldoctor'), ('DENTIST', 'dentist'), ('ONCOLOGIST', 'oncologist'), ('ortho', 'orthopaedic'), ('OPTICIAN', 'optician'), ('PAEDIATRICIAN', 'paediatrician'), ('cardio', 'cardiologist')], default='generaldotor', max_length=100)),
                ('hospital', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
